import type { SavedConnection } from "@/types/connections"
import { quoteIdentifier, quoteSqlLiteral } from "@/helpers/connections"

export type CreateTableColumnSpec = {
  name: string
  dataType: string
  size: string
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
  defaultValue: string
  comment: string
}

export type CreateTableForeignKeySpec = {
  sourceColumn: string
  referencedSchemaName?: string
  referencedTableName: string
  referencedColumnName: string
  onDelete?: string
  onUpdate?: string
}

export function normalizeDefaultValue(value: string) {
  const trimmed = value.trim()

  if (
    /^(CURRENT_TIMESTAMP|CURRENT_DATE|CURRENT_TIME|NOW\(\)|TRUE|FALSE)$/i.test(trimmed) ||
    /^-?\d+(\.\d+)?$/.test(trimmed)
  ) {
    return trimmed
  }

  return quoteSqlLiteral(trimmed)
}

export function buildCreateTableColumnDefinition(
  connection: SavedConnection,
  column: CreateTableColumnSpec
) {
  const columnName = quoteIdentifier(connection.databaseType, column.name)
  const parts = [columnName]
  const baseType = column.dataType
  const typeWithSize =
    column.size &&
    /^(CHAR|NCHAR|VARCHAR|NVARCHAR|BINARY|VARBINARY|DECIMAL|NUMERIC|NUMBER|ENUM|FLOAT|DOUBLE)$/.test(baseType)
      ? `${baseType}(${column.size})`
      : baseType

  if (connection.databaseType === "sqlite" && column.autoIncrement && column.primaryKey) {
    return `${columnName} INTEGER PRIMARY KEY AUTOINCREMENT`
  }

  parts.push(typeWithSize)

  if (column.autoIncrement) {
    if (connection.databaseType === "mysql" || connection.databaseType === "mariadb") {
      parts.push("AUTO_INCREMENT")
    } else if (connection.databaseType === "postgresql") {
      parts.push("GENERATED BY DEFAULT AS IDENTITY")
    } else if (connection.databaseType === "sqlserver") {
      parts.push("IDENTITY(1,1)")
    }
  }

  if (column.notNull) {
    parts.push("NOT NULL")
  }

  if (column.defaultValue) {
    parts.push(`DEFAULT ${normalizeDefaultValue(column.defaultValue)}`)
  }

  if (column.primaryKey && !(connection.databaseType === "sqlite" && column.autoIncrement)) {
    parts.push("PRIMARY KEY")
  }

  if (column.comment && (connection.databaseType === "mysql" || connection.databaseType === "mariadb")) {
    parts.push(`COMMENT ${quoteSqlLiteral(column.comment)}`)
  }

  return parts.join(" ")
}

function buildForeignKeyConstraintName(
  connection: SavedConnection,
  tableName: string,
  foreignKey: CreateTableForeignKeySpec,
  index: number
) {
  const suffix = `${tableName}_${foreignKey.sourceColumn}_${foreignKey.referencedTableName}_${foreignKey.referencedColumnName}_${index}`
    .replace(/[^A-Za-z0-9_]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")

  if (connection.databaseType === "sqlserver") {
    return `[fk_${suffix}]`
  }

  if (connection.databaseType === "postgresql") {
    return `"fk_${suffix.replace(/"/g, '""')}"`
  }

  return `\`fk_${suffix.replace(/`/g, "``")}\``
}

export function buildCreateTableForeignKeyDefinition(
  connection: SavedConnection,
  tableName: string,
  foreignKey: CreateTableForeignKeySpec,
  index: number,
  defaultSchemaName: string
) {
  const sourceColumn = quoteIdentifier(connection.databaseType, foreignKey.sourceColumn)
  const referencedSchemaName = foreignKey.referencedSchemaName?.trim() || defaultSchemaName
  const referencedTable = quoteIdentifier(connection.databaseType, foreignKey.referencedTableName)
  const referencedColumn = quoteIdentifier(connection.databaseType, foreignKey.referencedColumnName)
  const referencedQualifiedTable =
    connection.databaseType === "sqlite"
      ? referencedTable
      : `${quoteIdentifier(connection.databaseType, referencedSchemaName)}.${referencedTable}`
  const actions = [foreignKey.onDelete?.trim(), foreignKey.onUpdate?.trim()]
    .map((action, actionIndex) => {
      if (!action) {
        return null
      }

      return `${actionIndex === 0 ? "ON DELETE" : "ON UPDATE"} ${action}`
    })
    .filter(Boolean)
    .join(" ")

  return `CONSTRAINT ${buildForeignKeyConstraintName(connection, tableName, foreignKey, index)} FOREIGN KEY (${sourceColumn}) REFERENCES ${referencedQualifiedTable} (${referencedColumn})${actions ? ` ${actions}` : ""}`
}
