import type { SavedConnection } from "@/types/connections"
import { quoteIdentifier, quoteSqlLiteral } from "@/helpers/connections"

export type CreateTableColumnSpec = {
  name: string
  dataType: string
  size: string
  unsigned?: boolean
  notNull: boolean
  primaryKey: boolean
  autoIncrement: boolean
  defaultValue: string
  comment: string
}

export type CreateTableForeignKeySpec = {
  sourceColumn: string
  referencedSchemaName?: string
  referencedTableName: string
  referencedColumnName: string
  onDelete?: string
  onUpdate?: string
}

export type CreateTableIndexSpec = {
  name: string
  columns: string[]
  unique: boolean
}

export function normalizeDefaultValue(value: string) {
  const trimmed = value.trim()

  if (
    /^(CURRENT_TIMESTAMP|CURRENT_DATE|CURRENT_TIME|NOW\(\)|TRUE|FALSE)$/i.test(trimmed) ||
    /^-?\d+(\.\d+)?$/.test(trimmed)
  ) {
    return trimmed
  }

  return quoteSqlLiteral(trimmed)
}

export function buildCreateTableColumnDefinition(
  connection: SavedConnection,
  column: CreateTableColumnSpec
) {
  const columnName = quoteIdentifier(connection.databaseType, column.name)
  const parts = [columnName]
  const baseType = column.dataType
  const typeWithSize =
    column.size &&
    /^(TINYINT|SMALLINT|MEDIUMINT|INT|INTEGER|BIGINT|CHAR|NCHAR|VARCHAR|NVARCHAR|BINARY|VARBINARY|DECIMAL|NUMERIC|NUMBER|ENUM|FLOAT|DOUBLE)$/.test(baseType)
      ? `${baseType}(${column.size})`
      : baseType

  if (connection.databaseType === "sqlite" && column.autoIncrement && column.primaryKey) {
    return `${columnName} INTEGER PRIMARY KEY AUTOINCREMENT`
  }

  parts.push(typeWithSize)

  if (
    column.unsigned &&
    (connection.databaseType === "mysql" || connection.databaseType === "mariadb") &&
    /^(TINYINT|SMALLINT|MEDIUMINT|INT|INTEGER|BIGINT|DECIMAL|NUMERIC|NUMBER|FLOAT|DOUBLE)$/i.test(
      baseType
    )
  ) {
    parts.push("UNSIGNED")
  }

  if (column.autoIncrement) {
    if (connection.databaseType === "mysql" || connection.databaseType === "mariadb") {
      parts.push("AUTO_INCREMENT")
    } else if (connection.databaseType === "postgresql") {
      parts.push("GENERATED BY DEFAULT AS IDENTITY")
    } else if (connection.databaseType === "sqlserver") {
      parts.push("IDENTITY(1,1)")
    }
  }

  if (column.notNull) {
    parts.push("NOT NULL")
  }

  if (column.defaultValue) {
    parts.push(`DEFAULT ${normalizeDefaultValue(column.defaultValue)}`)
  }

  if (column.primaryKey && !(connection.databaseType === "sqlite" && column.autoIncrement)) {
    parts.push("PRIMARY KEY")
  }

  if (column.comment && (connection.databaseType === "mysql" || connection.databaseType === "mariadb")) {
    parts.push(`COMMENT ${quoteSqlLiteral(column.comment)}`)
  }

  return parts.join(" ")
}

export function buildForeignKeyConstraintName(
  connection: SavedConnection,
  tableName: string,
  foreignKey: CreateTableForeignKeySpec,
  index: number
) {
  const suffix = `${tableName}_${foreignKey.sourceColumn}_${foreignKey.referencedTableName}_${foreignKey.referencedColumnName}_${index}`
    .replace(/[^A-Za-z0-9_]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")

  if (connection.databaseType === "sqlserver") {
    return `[fk_${suffix}]`
  }

  if (connection.databaseType === "postgresql") {
    return `"fk_${suffix.replace(/"/g, '""')}"`
  }

  return `\`fk_${suffix.replace(/`/g, "``")}\``
}

export function buildTableIndexName(tableName: string, columnNames: string[] | string, index: number) {
  const columns = Array.isArray(columnNames) ? columnNames : [columnNames]
  const suffix = `${tableName}_${columns.join("_")}_${index}`
    .replace(/[^A-Za-z0-9_]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")

  return `idx_${suffix}`.toLowerCase()
}

export function buildCreateTableIndexDefinition(
  connection: SavedConnection,
  tableName: string,
  index: CreateTableIndexSpec,
  indexNumber: number,
  defaultSchemaName: string
) {
  const indexName = index.name.trim() || buildTableIndexName(tableName, index.columns, indexNumber)
  const columnNames = index.columns.map((column) => column.trim()).filter(Boolean)
  const quotedIndexName = quoteIdentifier(connection.databaseType, indexName)
  const quotedColumnNames = columnNames.map((columnName) => quoteIdentifier(connection.databaseType, columnName))

  if (!columnNames.length) {
    throw new Error("Informe ao menos uma coluna válida para criar o índice.")
  }

  const uniquePrefix = index.unique ? "UNIQUE " : ""

  if (connection.databaseType === "sqlite") {
    return `CREATE ${uniquePrefix}INDEX ${quotedIndexName} ON ${quoteIdentifier(connection.databaseType, tableName)} (${quotedColumnNames.join(", ")})`
  }

  const quotedSchema = quoteIdentifier(connection.databaseType, defaultSchemaName)
  const quotedTable = quoteIdentifier(connection.databaseType, tableName)

  return `CREATE ${uniquePrefix}INDEX ${quotedIndexName} ON ${quotedSchema}.${quotedTable} (${quotedColumnNames.join(", ")})`
}

export function buildDropTableIndexSql(
  connection: SavedConnection,
  schemaName: string,
  tableName: string,
  indexName: string
) {
  const quotedIndexName = quoteIdentifier(connection.databaseType, indexName)

  if (connection.databaseType === "mysql" || connection.databaseType === "mariadb") {
    const qualifiedTable = `${quoteIdentifier(connection.databaseType, schemaName)}.${quoteIdentifier(
      connection.databaseType,
      tableName
    )}`
    return `ALTER TABLE ${qualifiedTable} DROP INDEX ${quotedIndexName}`
  }

  if (connection.databaseType === "postgresql") {
    return `DROP INDEX IF EXISTS ${quoteIdentifier(connection.databaseType, schemaName)}.${quotedIndexName}`
  }

  if (connection.databaseType === "sqlserver") {
    const qualifiedTable = `${quoteIdentifier(connection.databaseType, schemaName)}.${quoteIdentifier(
      connection.databaseType,
      tableName
    )}`
    return `DROP INDEX ${quotedIndexName} ON ${qualifiedTable}`
  }

  return `DROP INDEX IF EXISTS ${quotedIndexName}`
}

export function buildCreateTableForeignKeyDefinition(
  connection: SavedConnection,
  tableName: string,
  foreignKey: CreateTableForeignKeySpec,
  index: number,
  defaultSchemaName: string
) {
  const sourceColumn = quoteIdentifier(connection.databaseType, foreignKey.sourceColumn)
  const referencedSchemaName = foreignKey.referencedSchemaName?.trim() || defaultSchemaName
  const referencedTable = quoteIdentifier(connection.databaseType, foreignKey.referencedTableName)
  const referencedColumn = quoteIdentifier(connection.databaseType, foreignKey.referencedColumnName)
  const referencedQualifiedTable =
    connection.databaseType === "sqlite"
      ? referencedTable
      : `${quoteIdentifier(connection.databaseType, referencedSchemaName)}.${referencedTable}`
  const actions = [foreignKey.onDelete?.trim(), foreignKey.onUpdate?.trim()]
    .map((action, actionIndex) => {
      if (!action) {
        return null
      }

      return `${actionIndex === 0 ? "ON DELETE" : "ON UPDATE"} ${action}`
    })
    .filter(Boolean)
    .join(" ")

  return `CONSTRAINT ${buildForeignKeyConstraintName(connection, tableName, foreignKey, index)} FOREIGN KEY (${sourceColumn}) REFERENCES ${referencedQualifiedTable} (${referencedColumn})${actions ? ` ${actions}` : ""}`
}
